################################################################################
Concuerror started with options:
  [{target,{registered_send_3,registered_send_3,[]}},
   {symbolic,true},
   {verbose,0},
   {timeout,1000},
   {files,["/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"]},
   {'after-timeout',infinite},
   {bound,2},
   {distributed,true},
   {'light-dpor',false}]
################################################################################
Erroneous interleaving 1:
* At step 8 process P exited abnormally
    Reason:
      {badarg,[{erlang,'!',
                       [child,foo],
                       [17,
                        {file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"}]}]}
    Stacktrace:
      [{erlang,'!',
               [child,foo],
               [17,
                {file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<registered_send_3.0.68905217>,[]])
    in erlang.erl line 2329
   2: P: ok = P.1 ! ok
    in registered_send_3.erl line 15
   3: Message (ok) from P reaches P.1
   4: P: true = erlang:register(child, P.1)
    in registered_send_3.erl line 16
   5: P.1: receives message (ok)
    in registered_send_3.erl line 11
   6: P.1: exits normally
   7: P: Exception raised by: child ! foo
    in registered_send_3.erl line 17
   8: P: exits abnormally
################################################################################
Erroneous interleaving 2:
* At step 7 process P exited abnormally
    Reason:
      {badarg,
          [{erlang,register,
               [child,P.1],
               [16,
                {file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"}]},
           {registered_send_3,registered_send_3,0,
               [{file,
                    "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"},
                {line,16}]}]}
    Stacktrace:
      [{erlang,register,
               [child,P.1],
               [16,
                {file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"}]},
       {registered_send_3,registered_send_3,0,
                          [{file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/registered_send_3.erl"},
                           {line,16}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<registered_send_3.0.68905217>,[]])
    in erlang.erl line 2329
   2: P: ok = P.1 ! ok
    in registered_send_3.erl line 15
   3: Message (ok) from P reaches P.1
   4: P.1: receives message (ok)
    in registered_send_3.erl line 11
   5: P.1: exits normally
   6: P: Exception raised by: erlang:register(child, P.1)
    in registered_send_3.erl line 16
   7: P: exits abnormally
################################################################################
Done! (Exit status: ok)
  Summary: 2 errors, 3/3 interleavings explored
