################################################################################
Concuerror started with options:
  [{target,{spawned_sender_crasher,spawned_sender_crasher,[]}},
   {symbolic,true},
   {verbose,0},
   {timeout,1000},
   {files,["/home/stavros/git/Concuerror/testsuite/suites/dpor/src/spawned_sender_crasher.erl"]},
   {'after-timeout',infinite},
   {bound,2},
   {distributed,true},
   {'light-dpor',false}]
################################################################################
Erroneous interleaving 1:
* At step 12 process P.1 exited abnormally
    Reason:
      {{badmatch,[one,two]},
       [{spawned_sender_crasher,receive_two,0,
            [{file,
                 "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/spawned_sender_crasher.erl"},
             {line,21}]}]}
    Stacktrace:
      [{spawned_sender_crasher,receive_two,0,
                               [{file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/spawned_sender_crasher.erl"},
                                {line,21}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<spawned_sender_crasher.0.34190977>,[]])
    in erlang.erl line 2188
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<spawned_sender_crasher.5.34190977>,[]])
    in erlang.erl line 2188
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<spawned_sender_crasher.5.34190977>,[]])
    in erlang.erl line 2188
   4: P: exits normally
   5: P.2: one = P.1 ! one
    in spawned_sender_crasher.erl line 26
   6: Message (one) from P.2 reaches P.1
   7: P.1: receives message (one)
    in spawned_sender_crasher.erl line 16
   8: P.2: exits normally
   9: P.3: two = P.1 ! two
    in spawned_sender_crasher.erl line 26
  10: Message (two) from P.3 reaches P.1
  11: P.1: receives message (two)
    in spawned_sender_crasher.erl line 18
  12: P.1: exits abnormally
  13: P.3: exits normally
################################################################################
Erroneous interleaving 2:
* At step 13 process P.1 exited abnormally
    Reason:
      {{badmatch,[two,one]},
       [{spawned_sender_crasher,receive_two,0,
            [{file,
                 "/home/stavros/git/Concuerror/testsuite/suites/dpor/src/spawned_sender_crasher.erl"},
             {line,20}]}]}
    Stacktrace:
      [{spawned_sender_crasher,receive_two,0,
                               [{file,"/home/stavros/git/Concuerror/testsuite/suites/dpor/src/spawned_sender_crasher.erl"},
                                {line,20}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<spawned_sender_crasher.0.34190977>,[]])
    in erlang.erl line 2188
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<spawned_sender_crasher.5.34190977>,[]])
    in erlang.erl line 2188
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<spawned_sender_crasher.5.34190977>,[]])
    in erlang.erl line 2188
   4: P: exits normally
   5: P.2: one = P.1 ! one
    in spawned_sender_crasher.erl line 26
   6: P.2: exits normally
   7: P.3: two = P.1 ! two
    in spawned_sender_crasher.erl line 26
   8: P.3: exits normally
   9: Message (two) from P.3 reaches P.1
  10: Message (one) from P.2 reaches P.1
  11: P.1: receives message (two)
    in spawned_sender_crasher.erl line 16
  12: P.1: receives message (one)
    in spawned_sender_crasher.erl line 18
  13: P.1: exits abnormally
################################################################################
Done! (Exit status: ok)
  Summary: 2 errors, 2/2 interleavings explored
