################################################################################
Concuerror started with options:
  [{after_timeout,infinity},
   {assume_racing,false},
   {delay_bound,infinity},
   {depth_bound,5000},
   {entry_point,{same_messages_3,same_messages_3,[]}},
   {files,["/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"]},
   {ignore_error,[]},
   {ignore_first_crash,true},
   {instant_delivery,false},
   {non_racing_system,[]},
   {optimal,true},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]}]
################################################################################
Erroneous interleaving 1:
* At step 15 process P exited abnormally
    Reason:
      {{nocatch,a},
       [{same_messages_3,same_messages_3,0,
                         [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                          {line,23}]}]}
    Stacktrace:
      [{same_messages_3,same_messages_3,0,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                         {line,23}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   3: P.1: a = P ! a
    in same_messages_3.erl line 13
   4: P.1: unlock = P ! unlock
    in same_messages_3.erl line 14
   5: P.1: exits normally
   6: Message (a) from P.1 reaches P
   7: Message (unlock) from P.1 reaches P
   8: P.2: b = P ! b
    in same_messages_3.erl line 13
   9: P.2: unlock = P ! unlock
    in same_messages_3.erl line 14
  10: P.2: exits normally
  11: Message (b) from P.2 reaches P
  12: Message (unlock) from P.2 reaches P
  13: P: receives message (unlock)
    in same_messages_3.erl line 19
  14: P: receives message (a)
    in same_messages_3.erl line 21
  15: P: exits abnormally ({{nocatch,a},[{same_messages_3,same_messages_3,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,23}]}]})
################################################################################
Erroneous interleaving 2:
* At step 14 process P exited abnormally
    Reason:
      {{nocatch,a},
       [{same_messages_3,same_messages_3,0,
                         [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                          {line,23}]}]}
    Stacktrace:
      [{same_messages_3,same_messages_3,0,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                         {line,23}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   3: P.1: a = P ! a
    in same_messages_3.erl line 13
   4: P.1: unlock = P ! unlock
    in same_messages_3.erl line 14
   5: P.1: exits normally
   6: Message (a) from P.1 reaches P
   7: P.2: b = P ! b
    in same_messages_3.erl line 13
   8: P.2: unlock = P ! unlock
    in same_messages_3.erl line 14
   9: P.2: exits normally
  10: Message (b) from P.2 reaches P
  11: Message (unlock) from P.2 reaches P
  12: P: receives message (unlock)
    in same_messages_3.erl line 19
  13: P: receives message (a)
    in same_messages_3.erl line 21
  14: P: exits abnormally ({{nocatch,a},[{same_messages_3,same_messages_3,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,23}]}]})
  15: Message (unlock) from P.1 reaches P
################################################################################
Erroneous interleaving 3:
* At step 15 process P exited abnormally
    Reason:
      {{nocatch,a},
       [{same_messages_3,same_messages_3,0,
                         [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                          {line,23}]}]}
    Stacktrace:
      [{same_messages_3,same_messages_3,0,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                         {line,23}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   3: P.1: a = P ! a
    in same_messages_3.erl line 13
   4: P.1: unlock = P ! unlock
    in same_messages_3.erl line 14
   5: P.1: exits normally
   6: Message (a) from P.1 reaches P
   7: P.2: b = P ! b
    in same_messages_3.erl line 13
   8: P.2: unlock = P ! unlock
    in same_messages_3.erl line 14
   9: P.2: exits normally
  10: Message (b) from P.2 reaches P
  11: Message (unlock) from P.1 reaches P
  12: Message (unlock) from P.2 reaches P
  13: P: receives message (unlock)
    in same_messages_3.erl line 19
  14: P: receives message (a)
    in same_messages_3.erl line 21
  15: P: exits abnormally ({{nocatch,a},[{same_messages_3,same_messages_3,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,23}]}]})
################################################################################
Erroneous interleaving 4:
* At step 13 process P exited abnormally
    Reason:
      {{nocatch,b},
       [{same_messages_3,same_messages_3,0,
                         [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                          {line,23}]}]}
    Stacktrace:
      [{same_messages_3,same_messages_3,0,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                         {line,23}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   3: P.1: a = P ! a
    in same_messages_3.erl line 13
   4: P.1: unlock = P ! unlock
    in same_messages_3.erl line 14
   5: P.1: exits normally
   6: P.2: b = P ! b
    in same_messages_3.erl line 13
   7: P.2: unlock = P ! unlock
    in same_messages_3.erl line 14
   8: P.2: exits normally
   9: Message (b) from P.2 reaches P
  10: Message (unlock) from P.2 reaches P
  11: P: receives message (unlock)
    in same_messages_3.erl line 19
  12: P: receives message (b)
    in same_messages_3.erl line 21
  13: P: exits abnormally ({{nocatch,b},[{same_messages_3,same_messages_3,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,23}]}]})
  14: Message (a) from P.1 reaches P
  15: Message (unlock) from P.1 reaches P
################################################################################
Erroneous interleaving 5:
* At step 14 process P exited abnormally
    Reason:
      {{nocatch,b},
       [{same_messages_3,same_messages_3,0,
                         [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                          {line,23}]}]}
    Stacktrace:
      [{same_messages_3,same_messages_3,0,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                         {line,23}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   3: P.1: a = P ! a
    in same_messages_3.erl line 13
   4: P.1: unlock = P ! unlock
    in same_messages_3.erl line 14
   5: P.1: exits normally
   6: P.2: b = P ! b
    in same_messages_3.erl line 13
   7: P.2: unlock = P ! unlock
    in same_messages_3.erl line 14
   8: P.2: exits normally
   9: Message (b) from P.2 reaches P
  10: Message (a) from P.1 reaches P
  11: Message (unlock) from P.2 reaches P
  12: P: receives message (unlock)
    in same_messages_3.erl line 19
  13: P: receives message (b)
    in same_messages_3.erl line 21
  14: P: exits abnormally ({{nocatch,b},[{same_messages_3,same_messages_3,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,23}]}]})
  15: Message (unlock) from P.1 reaches P
################################################################################
Erroneous interleaving 6:
* At step 15 process P exited abnormally
    Reason:
      {{nocatch,b},
       [{same_messages_3,same_messages_3,0,
                         [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                          {line,23}]}]}
    Stacktrace:
      [{same_messages_3,same_messages_3,0,
                        [{file,"/home/stavros/git/Concuerror/tests/suites/dpor_tests/src/same_messages_3.erl"},
                         {line,23}]}]
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<same_messages_3.3.112068030>,[]])
    in erlang.erl line 2329
   3: P.1: a = P ! a
    in same_messages_3.erl line 13
   4: P.1: unlock = P ! unlock
    in same_messages_3.erl line 14
   5: P.1: exits normally
   6: P.2: b = P ! b
    in same_messages_3.erl line 13
   7: P.2: unlock = P ! unlock
    in same_messages_3.erl line 14
   8: P.2: exits normally
   9: Message (b) from P.2 reaches P
  10: Message (a) from P.1 reaches P
  11: Message (unlock) from P.1 reaches P
  12: Message (unlock) from P.2 reaches P
  13: P: receives message (unlock)
    in same_messages_3.erl line 19
  14: P: receives message (b)
    in same_messages_3.erl line 21
  15: P: exits abnormally ({{nocatch,b},[{same_messages_3,same_messages_3,0,[{file,[47,104,111,109,101,47,115,116,97|...]},{line,23}]}]})
################################################################################
Concuerror Info:
--------------------------------------------------------------------------------
Instrumented: same_messages_3
Instrumented: io_lib
Instrumented: gen_server
Hijacked application_controller
Instrumented: erlang
################################################################################
Done! (Exit status: completed)
  Summary: 6 errors, 6/6 interleavings explored
